### ISSUE TITLE
카카오톡이나 메일 등의 뱃지도 정보를 띄워줄 수 있을까요?

### ISSUE THREAD

**Issue by thegreatkingbear** [min-uuu/golden_minuuu_btt_preset#1]
깔끔하고 정말 좋은 것 같습니다!
그런데 카카오톡 뱃지도 (안 읽은 카카오톡이나 메일이 있을 경우 해당 아이콘과 함께 안 읽은 갯수가 나오게 함)
뜨게 할 수 있을까요?
골든카오스의 이 기능이 저에게는 꽤 유용하더라구요. (카톡은 위챗의 그것을 살짝 변경해서 썼습니다)

**Comment by min-uuu** [comment]
해당 기능은 btt 기본 위젯 중에서 dock widget을 사용하시면 될 거 같습니다.
configuration에 들어가셔서 왼쪽에서 2번째 세션에서 app switcher widget을 삭제하시고 해당 세션 아래에 + 버튼을 눌러 뜨는 팝업창에서 
Touch bar widget -> dock widget을 클릭하시고 설정을 다른 액션들과 같게 설정하시면 해당 기능을 사용하실 수 있을 것 같습니다.
