### ISSUE TITLE
command+space 입력 시 custom touchbar hide

### ISSUE THREAD

**Issue by dollce** [min-uuu/golden_minuuu_btt_preset#4]
command+space 입력 시 기본 터치바와 커스텀 터치바 사이를 전환하는 키로 동작하고 기존에 사용중이던 숏컷이 동작하지 않습니다. 
해당 단축키를 없앨 수 있나요?

**Comment by min-uuu** [comment]
안녕하세요!
제가 만든 프리셋을 사용하고 계시다니 정말 감사합니다.
다른 숏컷에서 cmd + space를 사용하고 계시다면
btt가 우선적으로 작동하여 해당 숏컷이 작동되지 않을 수 있습니다.
이 문제는 btt에서 configuration -> keyboard 에서 해당 숏컷을 삭제거나 다른 키입력으로 수정하시면 됩니다!
문제가 해결되길 바랍니다!

________________________________
From: Issac Newton ***@***.***>
Sent: Tuesday, May 25, 2021 7:13:54 AM
To: min-uuu/GoldenRabbit-BTT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [min-uuu/GoldenRabbit-BTT] command+space 입력 시 custom touchbar hide (#4)


command+space 입력 시 기본 터치바와 커스텀 터치바 사이를 전환하는 키로 동작하고 기존에 사용중이던 숏컷이 동작하지 않습니다.
해당 단축키를 없앨 수 있나요?

**Comment by dollce** [comment]
감사합니다 해결되었습니다.
